name: Java CI/CD with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build --exclude-task test --warning-mode all

  # 빌드 후 EC2에서 백그라운드로 Java 애플리케이션 실행
  deploy-to-ec2:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Upload built application to EC2
        run: |
          scp -i simter.pem "Users/sujin/Documents/예소/simter/build/libs/simter-0.0.1-SNAPSHOT.jar" ubuntu@3.37.213.59:/home/ubuntu

      - name: Stop existing application
        run: |
          ssh -i "simter.pem" ubuntu@3.37.213.59 "pkill -f 'java -jar /home/ubuntu/simter-0.0.1-SNAPSHOT.jar' || true"
      - name: env
        run: |
          export $(cat .env | xargs)
      - name: Start new application in the background without specifying a port
        run: |
          ssh -i "simter.pem" ubuntu@3.37.213.59 "nohup java -jar /home/ubuntu/simter-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &"
