name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PW: ${{ secrets.DB_PW }}
      DB_ROOTPW: ${{ secrets.DB_ROOTPW }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OAUTH_ID: ${{ secrets.OAUTH_ID }}
      OAUTH_PW: ${{ secrets.OAUTH_PW }}
      KAKAO_ID: ${{ secrets.KAKAO_ID }}
      KAKAO_URI: ${{ secrets.KAKAO_URI }}
      KAKAO_SECRET: ${{ secrets.KAKAO_SECRET }}
      MAIL_NAME: ${{ secrets.MAIL_NAME }}
      MAIL_PW: ${{ secrets.MAIL_PW }}
      CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      SERVER_URL: ${{ secrets.SERVER_URL }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
